package io.github.yanagikh.dotconvert

object MobileStrings {
    private val values = mapOf(
        "en" to mapOf(
            "subtitle" to "Safe native conversion for images, text, and structured tables.",
            "language" to "Language",
            "source" to "1. Source file",
            "choose" to "Choose file",
            "no_file" to "No file selected",
            "target" to "2. Output format",
            "quality" to "Image quality",
            "debug" to "Debug mode",
            "show_log" to "Show debug log",
            "hide_log" to "Hide debug log",
            "clear" to "Clear log",
            "export" to "Export log",
            "convert" to "Choose output and convert",
            "ready" to "Ready. The system file picker controls the output location.",
            "unsupported" to "This Android build supports PNG/JPEG/WebP image output, text formats, and JSON/JSONL/CSV/TSV data conversion.",
            "failed" to "Conversion failed",
            "complete" to "Conversion complete",
            "warning_title" to "Review conversion risks",
            "continue" to "Continue",
            "cancel" to "Cancel",
            "same-format" to "The file will be re-encoded in the same format.",
            "lossy-image" to "The selected image format can reduce quality.",
            "alpha-loss" to "JPEG cannot preserve transparency; transparent areas become white.",
            "animation-loss" to "Animated GIF input is converted from its first frame.",
            "formatting-loss" to "Plain text output cannot preserve formatting or embedded media.",
            "tabular-only" to "CSV and TSV output require flat object rows.",
            "debug_on" to "Debug logging enabled.",
            "debug_off" to "Debug logging disabled.",
            "working" to "Converting. The output is not opened until temporary conversion succeeds.",
        ),
        "zh" to mapOf(
            "subtitle" to "使用原生功能安全轉換圖片、文字與結構化表格。",
            "language" to "語言",
            "source" to "1. 來源檔案",
            "choose" to "選擇檔案",
            "no_file" to "尚未選擇檔案",
            "target" to "2. 輸出格式",
            "quality" to "圖片品質",
            "debug" to "除錯模式",
            "show_log" to "顯示除錯日誌",
            "hide_log" to "隱藏除錯日誌",
            "clear" to "清除日誌",
            "export" to "匯出日誌",
            "convert" to "選擇輸出並轉換",
            "ready" to "已就緒。輸出位置由系統檔案選擇器控制。",
            "unsupported" to "Android 版支援 PNG/JPEG/WebP 圖片輸出、文字格式，以及 JSON/JSONL/CSV/TSV 資料轉換。",
            "failed" to "轉換失敗",
            "complete" to "轉換完成",
            "warning_title" to "確認轉換風險",
            "continue" to "繼續",
            "cancel" to "取消",
            "same-format" to "檔案會使用相同格式重新編碼。",
            "lossy-image" to "選擇的圖片格式可能降低畫質。",
            "alpha-loss" to "JPEG 無法保留透明度；透明區域會變成白色。",
            "animation-loss" to "動畫 GIF 只會轉換第一幀。",
            "formatting-loss" to "純文字輸出無法保留格式或嵌入媒體。",
            "tabular-only" to "CSV 與 TSV 輸出需要平面的物件列。",
            "debug_on" to "已啟用除錯日誌。",
            "debug_off" to "已停用除錯日誌。",
            "working" to "正在轉換。暫存轉換成功前不會開啟輸出檔。",
        ),
        "ja" to mapOf(
            "subtitle" to "画像、テキスト、構造化表をネイティブ機能で安全に変換します。",
            "language" to "言語",
            "source" to "1. 変換元ファイル",
            "choose" to "ファイルを選択",
            "no_file" to "ファイルが選択されていません",
            "target" to "2. 出力形式",
            "quality" to "画像品質",
            "debug" to "デバッグモード",
            "show_log" to "デバッグログを表示",
            "hide_log" to "デバッグログを隠す",
            "clear" to "ログを消去",
            "export" to "ログを書き出す",
            "convert" to "出力先を選択して変換",
            "ready" to "準備完了。出力先はシステムのファイル選択画面で指定します。",
            "unsupported" to "Android 版は PNG/JPEG/WebP 画像出力、テキスト形式、JSON/JSONL/CSV/TSV データ変換に対応します。",
            "failed" to "変換失敗",
            "complete" to "変換完了",
            "warning_title" to "変換リスクの確認",
            "continue" to "続行",
            "cancel" to "キャンセル",
            "same-format" to "同じ形式で再エンコードします。",
            "lossy-image" to "選択した画像形式では画質が低下する場合があります。",
            "alpha-loss" to "JPEG は透明度を保持できず、透明部分は白になります。",
            "animation-loss" to "アニメーション GIF は先頭フレームだけを変換します。",
            "formatting-loss" to "プレーンテキスト出力は書式や埋め込みメディアを保持できません。",
            "tabular-only" to "CSV と TSV の出力には平坦なオブジェクト行が必要です。",
            "debug_on" to "デバッグログを有効にしました。",
            "debug_off" to "デバッグログを無効にしました。",
            "working" to "変換中です。一時変換が成功するまで出力ファイルは開きません。",
        ),
    )

    fun get(language: String, key: String): String =
        values[language]?.get(key) ?: values.getValue("en")[key] ?: key
}
